package com.alientech.treeid

object Index {
    val images: HashMap<String, Int> = hashMapOf(
        "fagus_grandifolia" to 214,
        "sambucus_canadensis" to 212,
        "castanea_dentata" to 193,
        "ulmus_americana" to 229,
        "ilex_opaca" to 181,
        "ostrya_virginiana" to 222,
        "carpinus_caroliniana" to 212,
        "sorbus_americana" to 161,
        "diospyros_virginiana" to 204,
        "prunus_americana" to 194,
        "liquidambar_styraciflua" to 171,
        "platanus_occidentalis" to 223,
        "hamamelis_virginiana" to 194,
        "taxodium_distichum" to 202,
        "abies_balsamea" to 196,
        "populus_balsamifera" to 191,
        "tilia_americana" to 235,
        "salix_bebbiana" to 178,
        "magnolia_macrophylla" to 190,
        "populus_grandidentata" to 206,
        "prunus_emarginata" to 228,
        "carya_cordiformis" to 214,
        "prunus_serotina" to 205,
        "populus_trichocarpa" to 71,
        "crataegus_douglasii" to 189,
        "robinia_pseudoacacia" to 230,
        "quercus_velutina" to 208,
        "picea_mariana" to 191,
        "nyssa_sylvatica" to 217,
        "salix_nigra" to 197,
        "quercus_douglasii" to 233,
        "parkinsonia_florida" to 317,
        "picea_pungens" to 274,
        "acer_negundo" to 225,
        "quercus_macrocarpa" to 203,
        "juglans_cinerea" to 225,
        "sabal_palmetto" to 158,
        "umbellularia_californica" to 185,
        "quercus_kelloggii" to 217,
        "aesculus_californica" to 190,
        "washingtonia_filifera" to 159,
        "aleurites_moluccanus" to 178,
        "quercus_chrysolepis" to 222,
        "quercus_montana" to 212,
        "quercus_muehlenbergii" to 172,
        "prunus_virginiana" to 226,
        "quercus_agrifolia" to 202,
        "sequoia_sempervirens" to 192,
        "pinus_edulis" to 265,
        "pseudotsuga_menziesii" to 189,
        "celtis_occidentalis" to 203,
        "asimina_triloba" to 198,
        "cercocarpus_ledifolius" to 209,
        "chilopsis_linearis" to 183,
        "juglans_nigra" to 112,
        "populus_deltoides" to 270,
        "tsuga_canadensis" to 209,
        "cercis_canadensis" to 169,
        "juniperus_virginiana" to 184,
        "pinus_strobus" to 212,
        "picea_engelmannii" to 301,
        "eucalyptus_globulus" to 191,
        "prunus_pensylvanica" to 192,
        "cornus_florida" to 182,
        "populus_fremontii" to 164,
        "sequoiadendron_giganteum" to 219,
        "ginkgo_biloba" to 215,
        "abies_grandis" to 206,
        "betula_populifolia" to 180,
        "zanthoxylum_clava_herculis" to 199,
        "gleditsia_triacanthos" to 233,
        "prosopis_glandulosa" to 195,
        "pinus_banksiana" to 160,
        "gymnocladus_dioicus" to 242,
        "pinus_attenuata" to 246,
        "chamaecyparis_lawsoniana" to 199,
        "pinus_flexilis" to 279,
        "pinus_taeda" to 223,
        "pinus_contorta" to 224,
        "pinus_palustris" to 180,
        "cupressus_macrocarpa" to 203,
        "tsuga_mertensiana" to 181,
        "populus_angustifolia" to 321,
        "catalpa_speciosa" to 229,
        "quercus_rubra" to 220,
        "thuja_occidentalis" to 220,
        "aesculus_glabra" to 186,
        "fraxinus_latifolia" to 172,
        "quercus_garryana" to 155,
        "maclura_pomifera" to 227,
        "cornus_nuttallii" to 194,
        "arbutus_menziesii" to 231,
        "taxus_brevifolia" to 210,
        "betula_papyrifera" to 204,
        "carya_illinoinensis" to 211,
        "carya_glabra" to 287,
        "quercus_palustris" to 279,
        "pinus_rigida" to 246,
        "pinus_ponderosa" to 207,
        "alnus_rubra" to 180,
        "acer_rubrum" to 191,
        "morus_rubra" to 228,
        "pinus_resinosa" to 229,
        "picea_rubens" to 212,
        "pinus_aristata" to 212,
        "juniperus_scopulorum" to 203,
        "carnegiea_gigantea" to 165,
        "amelanchier_alnifolia" to 189,
        "sassafras_albidum" to 194,
        "salix_scouleriana" to 242,
        "carya_ovata" to 218,
        "quercus_imbricaria" to 213,
        "pinus_echinata" to 220,
        "acer_saccharinum" to 239,
        "pinus_monophylla" to 199,
        "picea_sitchensis" to 178,
        "ulmus_rubra" to 101,
        "rhus_glabra" to 175,
        "catalpa_bignonioides" to 188,
        "quercus_virginiana" to 201,
        "magnolia_grandiflora" to 171,
        "quercus_falcata" to 209,
        "abies_lasiocarpa" to 216,
        "acer_saccharum" to 230,
        "pinus_lambertiana" to 244,
        "quercus_bicolor" to 100,
        "acacia_farnesiana" to 122,
        "betula_lenta" to 189,
        "larix_laricina" to 188,
        "notholithocarpus_densiflorus" to 226,
        "heteromeles_arbutifolia" to 183,
        "ailanthus_altissima" to 185,
        "populus_tremuloides" to 202,
        "liriodendron_tulipifera" to 174,
        "juniperus_osteosperma" to 199,
        "fraxinus_velutina" to 305,
        "pinus_virginiana" to 255,
        "betula_occidentalis" to 221,
        "crataegus_pruinosa" to 49,
        "tsuga_heterophylla" to 191,
        "thuja_plicata" to 191,
        "platanus_racemosa" to 66,
        "pinus_monticola" to 255,
        "fraxinus_americana" to 225,
        "abies_concolor" to 244,
        "morus_alba" to 164,
        "quercus_alba" to 231,
        "picea_glauca" to 173,
        "pinus_albicaulis" to 27,
        "ilex_vomitoria" to 156,
        "betula_alleghaniensis" to 197,
    )

    val names: HashMap<String, String> = hashMapOf(
        "fagus_grandifolia" to "American Beech",
        "sambucus_canadensis" to "American Elderberry",
        "castanea_dentata" to "American Chestnut",
        "ulmus_americana" to "American Elm",
        "ilex_opaca" to "American Holly",
        "ostrya_virginiana" to "American Hophornbeam",
        "carpinus_caroliniana" to "American Hornbeam",
        "sorbus_americana" to "American Mountain Ash",
        "diospyros_virginiana" to "American Persimmon",
        "prunus_americana" to "American Plum",
        "liquidambar_styraciflua" to "American Sweetgum",
        "platanus_occidentalis" to "American Sycamore",
        "hamamelis_virginiana" to "American Witch-Hazel",
        "taxodium_distichum" to "Baldcypress",
        "abies_balsamea" to "Balsam Fir",
        "populus_balsamifera" to "Balsam Poplar",
        "tilia_americana" to "Basswood",
        "salix_bebbiana" to "Bebb's Willow",
        "magnolia_macrophylla" to "Bigleaf Magnolia",
        "populus_grandidentata" to "Bigtooth Aspen",
        "prunus_emarginata" to "Bitter Cherry",
        "carya_cordiformis" to "Bitternut Hickory",
        "prunus_serotina" to "Black Cherry",
        "populus_trichocarpa" to "Black Cottonwood",
        "crataegus_douglasii" to "Black Hawthorn",
        "robinia_pseudoacacia" to "Black Locust",
        "quercus_velutina" to "Black Oak",
        "picea_mariana" to "Black Spruce",
        "nyssa_sylvatica" to "Black Tupelo",
        "salix_nigra" to "Black Willow",
        "quercus_douglasii" to "Blue Oak",
        "parkinsonia_florida" to "Blue Palo Verde",
        "picea_pungens" to "Blue Spruce",
        "acer_negundo" to "Box Elder",
        "quercus_macrocarpa" to "Bur Oak",
        "juglans_cinerea" to "Butternut",
        "sabal_palmetto" to "Cabbage Palmetto",
        "umbellularia_californica" to "California Bay",
        "quercus_kelloggii" to "California Black Oak",
        "aesculus_californica" to "California Buckeye",
        "washingtonia_filifera" to "California Fan Palm",
        "aleurites_moluccanus" to "Candlenut",
        "quercus_chrysolepis" to "Canyon Live Oak",
        "quercus_montana" to "Chestnut Oak",
        "quercus_muehlenbergii" to "Chinkapin Oak",
        "prunus_virginiana" to "Chokecherry",
        "quercus_agrifolia" to "Coast Live Oak",
        "sequoia_sempervirens" to "Coast Redwood",
        "pinus_edulis" to "Colorado Pinyon",
        "pseudotsuga_menziesii" to "Douglas-Fir",
        "celtis_occidentalis" to "Common Hackberry",
        "asimina_triloba" to "Common Pawpaw",
        "cercocarpus_ledifolius" to "Curl-leaf Mountain Mahogany",
        "chilopsis_linearis" to "Desert Willow",
        "juglans_nigra" to "Eastern Black Walnut",
        "populus_deltoides" to "Eastern Cottonwood",
        "tsuga_canadensis" to "Eastern Hemlock",
        "cercis_canadensis" to "Eastern Redbud",
        "juniperus_virginiana" to "Eastern Redcedar",
        "pinus_strobus" to "Eastern White Pine",
        "picea_engelmannii" to "Engelmann Spruce",
        "eucalyptus_globulus" to "Eurabbie",
        "prunus_pensylvanica" to "Fire Cherry",
        "cornus_florida" to "Flowering Dogwood",
        "populus_fremontii" to "Fremont Cottonwood",
        "sequoiadendron_giganteum" to "Giant Sequoia",
        "ginkgo_biloba" to "Ginkgo",
        "abies_grandis" to "Grand Fir",
        "betula_populifolia" to "Gray Birch",
        "zanthoxylum_clava-herculis" to "Hercules' Club",
        "gleditsia_triacanthos" to "Honey Locust",
        "prosopis_glandulosa" to "Honey Mesquite",
        "pinus_banksiana" to "Jack Pine",
        "gymnocladus_dioicus" to "Kentucky Coffeetree",
        "pinus_attenuata" to "Knobcone Pine",
        "chamaecyparis_lawsoniana" to "Lawson's Cypress",
        "pinus_flexilis" to "Limber Pine",
        "pinus_taeda" to "Loblolly Pine",
        "pinus_contorta" to "Lodgepole Pine",
        "pinus_palustris" to "Longleaf Pine",
        "cupressus_macrocarpa" to "Monterey Cypress",
        "tsuga_mertensiana" to "Mountain Hemlock",
        "populus_angustifolia" to "Narrowleaf Cottonwood",
        "catalpa_speciosa" to "Northern Catalpa",
        "quercus_rubra" to "Northern Red Oak",
        "thuja_occidentalis" to "Northern Whitecedar",
        "aesculus_glabra" to "Ohio Buckeye",
        "fraxinus_latifolia" to "Oregon Ash",
        "quercus_garryana" to "Oregon Oak",
        "maclura_pomifera" to "Osage-Orange",
        "cornus_nuttallii" to "Pacific Dogwood",
        "arbutus_menziesii" to "Pacific Madrone",
        "taxus_brevifolia" to "Pacific Yew",
        "betula_papyrifera" to "Paper Birch",
        "carya_illinoinensis" to "Pecan",
        "carya_glabra" to "Pignut Hickory",
        "quercus_palustris" to "Pin Oak",
        "pinus_rigida" to "Pitch Pine",
        "pinus_ponderosa" to "Ponderosa Pine",
        "alnus_rubra" to "Red Alder",
        "acer_rubrum" to "Red Maple",
        "morus_rubra" to "Red Mulberry",
        "pinus_resinosa" to "Red Pine",
        "picea_rubens" to "Red Spruce",
        "pinus_aristata" to "Bristlecone Pine",
        "juniperus_scopulorum" to "Rocky Mountain Juniper",
        "carnegiea_gigantea" to "Saguaro",
        "amelanchier_alnifolia" to "Saskatoon",
        "sassafras_albidum" to "Sassafras",
        "salix_scouleriana" to "Scouler's Willow",
        "carya_ovata" to "Shagbark Hickory",
        "quercus_imbricaria" to "Shingle Oak",
        "pinus_echinata" to "Shortleaf Pine",
        "acer_saccharinum" to "Silver Maple",
        "pinus_monophylla" to "Singleleaf Pinyon",
        "picea_sitchensis" to "Sitka Spruce",
        "ulmus_rubra" to "Slippery Elm",
        "rhus_glabra" to "Smooth Sumac",
        "catalpa_bignonioides" to "Southern Catalpa",
        "quercus_virginiana" to "Southern Live Oak",
        "magnolia_grandiflora" to "Southern Magnolia",
        "quercus_falcata" to "Southern Red Oak",
        "abies_lasiocarpa" to "Subalpine Fir",
        "acer_saccharum" to "Sugar Maple",
        "pinus_lambertiana" to "Sugar Pine",
        "quercus_bicolor" to "Swamp White Oak",
        "acacia_farnesiana" to "Sweet Acacia",
        "betula_lenta" to "Sweet Birch",
        "larix_laricina" to "Tamarack",
        "notholithocarpus_densiflorus" to "Tanoak",
        "heteromeles_arbutifolia" to "Toyon",
        "ailanthus_altissima" to "Tree-Of-Heaven",
        "populus_tremuloides" to "Trembling Aspen",
        "liriodendron_tulipifera" to "Tulip Tree",
        "juniperus_osteosperma" to "Utah Juniper",
        "fraxinus_velutina" to "Velvet Ash",
        "pinus_virginiana" to "Virginia Pine",
        "betula_occidentalis" to "Water Birch",
        "crataegus_pruinosa" to "Waxy-Fruited Hawthorn",
        "tsuga_heterophylla" to "Western Hemlock",
        "larix_occidentalis" to "Western Larch",
        "thuja_plicata" to "Western Redcedar",
        "platanus_racemosa" to "Western Sycamore",
        "pinus_monticola" to "Western White Pine",
        "fraxinus_americana" to "White Ash",
        "abies_concolor" to "White Fir",
        "morus_alba" to "White Mulberry",
        "quercus_alba" to "White Oak",
        "picea_glauca" to "White Spruce",
        "pinus_albicaulis" to "Whitebark Pine",
        "ilex_vomitoria" to "Yaupon Holly",
        "betula_alleghaniensis" to "Yellow Birch"
    )
}