from PIL import Image, UnidentifiedImageError
from os import listdir
from math import floor

species = [
    "fagus grandifolia",
    "sambucus canadensis",
    "castanea dentata",
    "ulmus americana",
    "ilex opaca",
    "ostrya virginiana",
    "carpinus caroliniana",
    "sorbus americana",
    "diospyros virginiana",
    "prunus americana",
    "liquidambar styraciflua",
    "platanus occidentalis",
    "hamamelis virginiana",
    "taxodium distichum",
    "abies balsamea",
    "populus balsamifera",
    "tilia americana",
    "salix bebbiana",
    "magnolia macrophylla",
    "populus grandidentata",
    "prunus emarginata",
    "carya cordiformis",
    "prunus serotina",
    "populus trichocarpa",
    "crataegus douglasii",
    "robinia pseudoacacia",
    "quercus velutina",
    "picea mariana",
    "nyssa sylvatica",
    "salix nigra",
    "quercus douglasii",
    "parkinsonia florida",
    "picea pungens",
    "acer negundo",
    "quercus macrocarpa",
    "juglans cinerea",
    "sabal palmetto",
    "umbellularia californica",
    "quercus kelloggii",
    "aesculus californica",
    "washingtonia filifera",
    "aleurites moluccanus",
    "quercus chrysolepis",
    "quercus montana",
    "quercus muehlenbergii",
    "prunus virginiana",
    "quercus agrifolia",
    "sequoia sempervirens",
    "pinus edulis",
    "pseudotsuga menziesii",
    "celtis occidentalis",
    "asimina triloba",
    "cercocarpus ledifolius",
    "chilopsis linearis",
    "juglans nigra",
    "populus deltoides",
    "tsuga canadensis",
    "cercis canadensis",
    "juniperus virginiana",
    "pinus strobus",
    "picea engelmannii",
    "eucalyptus globulus",
    "prunus pensylvanica",
    "cornus florida",
    "populus fremontii",
    "sequoiadendron giganteum",
    "ginkgo biloba",
    "abies grandis",
    "betula populifolia",
    "zanthoxylum clava-herculis",
    "gleditsia triacanthos",
    "prosopis glandulosa",
    "pinus banksiana",
    "gymnocladus dioicus",
    "pinus attenuata",
    "chamaecyparis lawsoniana",
    "pinus flexilis",
    "pinus taeda",
    "pinus contorta",
    "pinus palustris",
    "cupressus macrocarpa",
    "tsuga mertensiana",
    "populus angustifolia",
    "catalpa speciosa",
    "quercus rubra",
    "thuja occidentalis",
    "aesculus glabra",
    "fraxinus latifolia",
    "quercus garryana",
    "maclura pomifera",
    "cornus nuttallii",
    "arbutus menziesii",
    "taxus brevifolia",
    "betula papyrifera",
    "carya illinoinensis",
    "carya glabra",
    "quercus palustris",
    "pinus rigida",
    "pinus ponderosa",
    "alnus rubra",
    "acer rubrum",
    "morus rubra",
    "pinus resinosa",
    "picea rubens",
    "pinus aristata",
    "juniperus scopulorum",
    "carnegiea gigantea",
    "amelanchier alnifolia",
    "sassafras albidum",
    "salix scouleriana",
    "carya ovata",
    "quercus imbricaria",
    "pinus echinata",
    "acer saccharinum",
    "pinus monophylla",
    "picea sitchensis",
    "ulmus rubra",
    "rhus glabra",
    "catalpa bignonioides",
    "quercus virginiana",
    "magnolia grandiflora",
    "quercus falcata",
    "abies lasiocarpa",
    "acer saccharum",
    "pinus lambertiana",
    "quercus bicolor",
    "acacia farnesiana",
    "betula lenta",
    "larix laricina",
    "notholithocarpus densiflorus",
    "heteromeles arbutifolia",
    "ailanthus altissima",
    "populus tremuloides",
    "liriodendron tulipifera",
    "juniperus osteosperma",
    "fraxinus velutina",
    "pinus virginiana",
    "betula occidentalis",
    "crataegus pruinosa",
    "tsuga heterophylla",
    "larix occidentalis",
    "thuja plicata",
    "platanus racemosa",
    "pinus monticola",
    "fraxinus americana",
    "abies concolor",
    "morus alba",
    "quercus alba",
    "picea glauca",
    "pinus albicaulis",
    "ilex vomitoria",
    "betula alleghaniensis"
]

t = 0

for specie in species:
    for filename in listdir(f"./images/{specie.replace(' ', '_')}"):
        try:
            specie_image = Image.open(f"./images/{specie.replace(' ', '_')}/{filename}")
            x_new = floor(float(specie_image.size[0])/2)
            y_new = floor(float(specie_image.size[1])/2)

            specie_image = specie_image.resize((x_new, y_new), 1)

            specie_image.save(f"./images_comp/{filename}", optimize=True, quality=100)
        except UnidentifiedImageError:
            print(f"image {filename} broken")

    t += 1
    print(f"finished {t}/152 species")
